# -*- coding: utf-8 -*-
"""MiniProjectCA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zi6yZwtGp7whHe3YJVNpgFSXEv8h0Uj6

# Mini Projet: Structure Fischer-Heun
#
"""

import math

"""# 1.1 Cartesian Numbers

Generates a canonical code for each block (block fingerprint – each code will have its own sparse table) (Lab 4, Ex. 1)
    
*1-push onto the stack; 0-pop from the stack*
"""

def cartesian_number(arr):
    code, stack = [], []
    for x in arr:
        while stack and stack[-1] > x:
            stack.pop()
            code.append(0)
        stack.append(x)
        code.append(1)
    while stack:
        stack.pop()
        code.append(0)
    return code

"""Divides array in B length blocks, our case 3 and applies cartesian_numbers, generating for each block a cartesian code."""

def cartesian_blocks(arr, B):
    codes = []
    for i in range(0, len(arr), B):
        block = arr[i:i+B]
        codes.append(cartesian_number(block))
    return codes

"""Recieves cartesian code calculated before and an initially empty array where we'll save and map the codes with indexes corresponding to the array's length, if 2 blocks have the same cartesian number they recieve the same index;"""

def canonical_id(code, dictionary):
    key = tuple(code)
    if key not in dictionary:
        dictionary[key] = len(dictionary)
    return dictionary[key]

"""mapping indexes obtained beforehand with the blocks"""

def canonical_table(arr, B):
    codes = cartesian_blocks(arr, B)
    d, ids = {}, []
    for c in codes:
        ids.append(canonical_id(c, d))
    return ids, d

"""# 1.2 Sparse Table

Build an empty sparse table: place the array values in the first column (intervals of length 2^0, with as many rows as elements in the array and
log2(array length) columns.
"""

def build_sparse_table(arr):
    n = len(arr)
    K = math.floor(math.log2(n)) + 1 if n > 0 else 1
    st = [[0]*K for _ in range(n)]
    for i in range(n):
        st[i][0] = arr[i]
    return st

"""Fill sparse table: 2nd column minima length 2^1, 3rd column minima length 2^2.."""

def fill_sparse_table(arr, st):
    n = len(arr)
    K = len(st[0])
    for j in range(1, K):
        for i in range(n - (1 << j) + 1):
            st[i][j] = min(st[i][j-1], st[i + (1 << (j-1))][j-1])
    return st

"""Helps us know where to search a query in the sparse table ex: we recieve a query of length 3, so we search for it in the 2nd column (3<2^2)

"""

def precompute_logs(n):
    log_table = [0]*(n+1)
    for i in range(2, n+1):
        log_table[i] = log_table[i//2] + 1 #parte intreaga
    return log_table

"""Finds minima"""

def query_rmq_sparse(L, R, st, log_table):
    length = R - L + 1
    if length <= 0:
        return float('inf')
    j = log_table[length]
    return min(st[L][j], st[R - (1 << j) + 1][j])

"""# 1.3 Block decomposing and Naive RMQ

Splits array into b length blocks, and finds minima, then adds it in another array
"""

def compute_block_minima(arr, B):
    minima = []
    for i in range(0, len(arr), B):
        block = arr[i:i+B]
        if block:
            minima.append(min(block))
    return minima

"""Finds minima between 2 positions"""

def naive_rmq(arr, L, R):
    if L > R or L < 0 or R >= len(arr):
        return float('inf')
    return min(arr[L:R+1])

"""# 2. Fischer-Heun structure

Builds Fischer-Heun structure
"""

def build_fischer_heun(arr, block_size=3):
    n = len(arr)
    if n == 0:
        return {}
    # 1. Blocks
    blocks = [arr[i:i+block_size] for i in range(0, n, block_size)]

    # 2. Canonic numbers
    block_types, canonical_dict = canonical_table(arr, block_size)

    # 3. Builds RMQ table for each block type using the first block to have that type
    block_rmq_tables = {}
    rep_index_per_type = {}
    for idx, t in enumerate(block_types):  # map each index for every block type
        if t not in rep_index_per_type:
            rep_index_per_type[t] = idx

    for t, idx in rep_index_per_type.items():
        block_values = blocks[idx]
        st = build_sparse_table(block_values)
        st = fill_sparse_table(block_values, st)
        logs = precompute_logs(len(block_values))
        block_rmq_tables[t] = {
            'sparse_table': st,
            'log_table': logs,
            'values': block_values
        }

    # 4. Block minima
    block_minima = compute_block_minima(arr, block_size)

    return {
        'arr': arr,
        'block_size': block_size,
        'blocks': blocks,
        'block_types': block_types,           # list with block types
        'block_rmq_tables': block_rmq_tables, # RMQ for representative values
        'block_minima': block_minima
    }

"""RMQ within the same block"""

def query_block_rmq(fh_data, block_index, L, R):
  ## Verify if block exists
    if block_index >= len(fh_data['blocks']):
        return float('inf')
    ### Make global indexes local
    block = fh_data['blocks'][block_index]
    block_start = block_index * fh_data['block_size']
    local_L = L - block_start
    local_R = R - block_start

    # Make sure the indexes are within the block limits
    local_L = max(0, local_L)
    local_R = min(len(block) - 1, local_R)

    ## If not:
    if local_L > local_R:
        return float('inf')

    # Small intervals we use minima (more efficient)
    if (local_R - local_L + 1) <= 2:
        return min(block[local_L:local_R+1])

    type_id = fh_data['block_types'][block_index] ## seach block type

    # Use Sparse Table
    if type_id in fh_data['block_rmq_tables']:
        block_data = fh_data['block_rmq_tables'][type_id]
        st = block_data['sparse_table']
        logs = block_data['log_table']
        return query_rmq_sparse(local_L, local_R, st, logs)
    else:
        # Fallback: use min()
        return min(block[local_L:local_R+1])

"""RMQ within [L, R]"""

def fischer_heun_rmq(fh_data, L, R):
    arr = fh_data['arr']
    block_size = fh_data['block_size']
    n = len(arr)
### query exists
    if L < 0 or R >= n or L > R:
        return float('inf')
## searching the blocks for the interval
    start_block = L // block_size
    end_block = R // block_size

    # Both numbers are in the same block
    if start_block == end_block:
        return query_block_rmq(fh_data, start_block, L, R)

    # Numbers are in separate block
    min_values = []

    #  Left block (partially)
    left_end = (start_block + 1) * block_size - 1 ##block limit
    if left_end >= n:
        left_end = n - 1
    min_left = query_block_rmq(fh_data, start_block, L, left_end) ## minima from L to block limit
    min_values.append(min_left)

    #  Right block (partially)
    right_start = end_block * block_size ## right limit for block
    # Making sure right_is not bigger than R
    if right_start <= R:
        min_right = query_block_rmq(fh_data, end_block, right_start, R) ## minima from right limit of block to R
        min_values.append(min_right)

    #  Middle block (if there are any)
    if end_block - start_block > 1: ## Blocks are not consecutives
        middle_min = naive_rmq(fh_data['block_minima'], start_block + 1, end_block - 1)
        min_values.append(middle_min)

    return min(min_values) ## final minima between right block, middle blocks and left block

"""# 3. Donnes du projet"""

if __name__ == "__main__":
    input_vector = [3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5, 8]
    block_size = 3
    queries = [(0, 2), (2, 8), (0, 11), (4, 5), (6, 10)]
    fh_structure = build_fischer_heun(input_vector, block_size)
    parts = [f"RMQ({L}, {R}) = {fischer_heun_rmq(fh_structure, L, R)}" for (L, R) in queries]
    print(" " + ", ".join(parts))